import type { SourceConfig, SourceRole } from "./types";

export const CORE_U2020_ROLES: SourceRole[] = [
  { name: "Administrators", description: "Has all rights except user management, query security log and view online users.", isReadOnly: false, isAdmin: true, canManageUsers: false },
  { name: "Advace optmiz", description: "for optimization team need", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Assurance User Group", description: "For Assurance User Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "CA Administrator Group", description: "CA administrator group has operation rights on all functions of the Certificate Authority Service.", isReadOnly: false, isAdmin: true, canManageUsers: false },
  { name: "CA Operator Group", description: "Has the permission to view the CA, Certificate Profile, Function Management, and HSM Management pages, and the permission to perform operations on other pages.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Configuration and DataBase", description: "Users can create, configure and modify NEs, the also can intiate traces and export HW status", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Core Group", description: "System Maintenance Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "CoreMaster", description: "System Maintenance Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "ECO Group", description: "For ECO to send commands", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Guests", description: "Guest User Group", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "HOFS Group", description: "System HOFS group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Huawei_CO-UMPT", description: "this group for Huawei users", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Huawei_Configuration and DataBase", description: "contains 200 site for Huawei Remote support Team", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Huawei_Core_Team_Group", description: "Huawei Core team", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Huawei_Team_Group", description: "Huawei_Team_Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "LST_OPTLOG_Group", description: "This group for users that can List Operation Log", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "Limited_Operator_Core", description: "for RAN users access to Core", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "MW_Operation", description: "MW users that need to ping and browse alarms only", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "Maintenance & RAN", description: "System Maintenance Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Maintenance Group", description: "System Maintenance Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Maintenance_Team_Extra", description: "Extra Commands for Maintenance Team", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Managers_And_TeamLeaders", description: "Top Management", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "Monitoring Group", description: "System Monitoring Group", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "NBI Admin Group", description: "It has the permissions on operations and interface configurations for all management interfaces.", isReadOnly: false, isAdmin: true, canManageUsers: false },
  { name: "NBI OpenAPI User Group", description: "Has device-level operation rights for all objects and application-level operation rights for northbound open APIs.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "NBI User Group", description: "Has permissions to perform operations on NBIs and configure interfaces on the web client.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "NBI_MML_Group", description: "Autin User", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "NFVOAccessRole", description: "Has the right to use some northbound APIs, which is the role provided for NFVO to call northbound APIs.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "NOC Operators", description: "Normal operator group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "NOC_Shift_Leaders", description: "NOC ShiftLeaders", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "NSSMFAccessRole", description: "Has the right to use some northbound APIs, which is the role provided for NSSMF to call northbound APIs.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Noc_operation_1", description: "Copy of Maintenance system role", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Operator Group", description: "System Operator Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Parlaiment", description: "System Operator Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Performance", description: "Users who need to see the stats, configuration and alarms of NE", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "Performance_monitor", description: "Specail group for Performance monitoring access", isReadOnly: true, isAdmin: false, canManageUsers: false },
  { name: "Planning", description: "for Planning Team", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Power_Team", description: "This group is trageting power team commands needed for battery manipulation", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "SMManagers", description: "Has permission to manage users, manage licenses, query security logs, view online users, and update ACL policies.", isReadOnly: false, isAdmin: true, canManageUsers: true },
  { name: "TSGroup", description: "System Operator Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "TascTowers_Team", description: "NOC", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "TascTowers_Team_Extra", description: "NOC", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "The role to invoke southbound APIs", description: "Indicates the role to invoke southbound APIs", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "Third-party Application System Access Role", description: "Has the right to use all northbound APIs, which is the role provided for Third-party Application System to call northbound APIs.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "UPRAccessRole", description: "UPR interconnection role", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "VAS Group", description: "VAS Team", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "VNFM User Group", description: "Core IaaS Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "VNFMAccessRole", description: "Has the right to use all northbound APIs, which is the role provided for CSM to call northbound APIs.", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "WebNIC User Group", description: "For WebNIC User Group", isReadOnly: false, isAdmin: false, canManageUsers: false },
  { name: "ntecoroles", description: "connection between NetEco & U2020", isReadOnly: false, isAdmin: false, canManageUsers: false },
];

export const CORE_U2020_HUAWEI_CONFIG: SourceConfig = {
  name: "Core U2020 Huawei",
  sourceIps: ["10.253.124.169"],
  blockedOperators: [],
  roles: CORE_U2020_ROLES,
  parseRules: {
    treatMmlAsNormal: true,
    readOnlyRolesAreViolation: true,
    treatAllAsNormal: false,
    isManualUpload: false
  }
};
